### Criar livro
POST http://localhost:3000/livros
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tZSI6IkVkdWFyZG8iLCJlbWFpbCI6ImVkdWFyZG9AZW1haWwuY29tIiwiaWF0IjoxNzc4NDU4MTE3LCJleHAiOjE3NzkwNjI5MTd9.vEE2zYkzMasmdEvmInoWrN2TWvi61ZQBAxJa-U0Dk7k

{
    "titulo": "Clean Code",
    "autor": "Robert Martin",
    "descricao": "Livro de como escrever código limpo",
    "isbn": "978-0132350"
}

### Listar livros
GET http://localhost:3000/livros

### Buscar livro por id
GET http://localhost:3000/livros/3

### Buscar livros disponiveis
GET http://localhost:3000/livros?disponivel=true

### Deletar livro
DELETE http://localhost:3000/livros/1

### Registrar
POST http://localhost:3000/auth/registrar
Content-Type: application/json

{
    "nome": "Eduardo",
    "email": "eduardo@email.com",
    "senha": "senha123"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "eduardo@email.com",
    "senha": "senha123"
}

### Criar empréstimo com token
POST http://localhost:3000/emprestimos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tZSI6IkVkdWFyZG8iLCJlbWFpbCI6ImVkdWFyZG9AZW1haWwuY29tIiwiaWF0IjoxNzc4NDU4MTE3LCJleHAiOjE3NzkwNjI5MTd9.vEE2zYkzMasmdEvmInoWrN2TWvi61ZQBAxJa-U0Dk7k

{
    "livroId": 3
}

### Listar empréstimos com token
GET http://localhost:3000/emprestimos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tZSI6IkVkdWFyZG8iLCJlbWFpbCI6ImVkdWFyZG9AZW1haWwuY29tIiwiaWF0IjoxNzc4NDU4MTE3LCJleHAiOjE3NzkwNjI5MTd9.vEE2zYkzMasmdEvmInoWrN2TWvi61ZQBAxJa-U0Dk7k

### Devolver empréstimo
PATCH http://localhost:3000/emprestimos/3/devolver
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibm9tZSI6IkVkdWFyZG8iLCJlbWFpbCI6ImVkdWFyZG9AZW1haWwuY29tIiwiaWF0IjoxNzc4NDU4MTE3LCJleHAiOjE3NzkwNjI5MTd9.vEE2zYkzMasmdEvmInoWrN2TWvi61ZQBAxJa-U0Dk7k

### Tentar criar empréstimo sem token
POST http://localhost:3000/emprestimos
Content-Type: application/json

{
    "livroId": 1
}

### Registrar segundo usuário
POST http://localhost:3000/auth/registrar
Content-Type: application/json

{
    "nome": "Ana",
    "email": "ana@email.com",
    "senha": "senha123"
}

### Tentar devolver empréstimo do Eduardo com token da Ana
PATCH http://localhost:3000/emprestimos/4/devolver
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibm9tZSI6IkFuYSIsImVtYWlsIjoiYW5hQGVtYWlsLmNvbSIsImlhdCI6MTc3ODQ1ODIwNiwiZXhwIjoxNzc5MDYzMDA2fQ.e09VABqIdFExf4ysopOzR0NWQL1FDwJZs3cUY4OSGWU