### Criar livro
POST http://localhost:3000/livros
Content-Type: application/json

{
    "titulo": "Clean Code",
    "autor": "Robert Martin",
    "descricao": "Livro de como escrever código limpo",
    "isbn": "978-0132350"
}

### Listar livros
GET http://localhost:3000/livros

### Buscar livro por id
GET http://localhost:3000/livros/3

### Buscar livros disponiveis
GET http://localhost:3000/livros?disponivel=true

### Deletar livro
DELETE http://localhost:3000/livros/1

### Criar empréstimo
POST http://localhost:3000/emprestimos
Content-Type: application/json

{
    "livroId": 1,
    "nomeUsuario": "Ana"
}

### Listar empréstimos
GET http://localhost:3000/emprestimos/

### Buscar empréstimos por ID
GET http://localhost:3000/emprestimos/1

### Listar empréstimos não devolvidos
GET http://localhost:3000/emprestimos?devolvido=false

### Devolver empréstimo
PATCH http://localhost:3000/emprestimos/2/devolver

### Tentar criar empréstimo em livro indisponível
POST http://localhost:3000/emprestimos
Content-Type: application/json

{
    "livroId": 1,
    "nomeUsuario": "Carlos"
}