version: '3.8'
services:
  api:
      build: .
      ports: 
        - "3000:3000"
      environment:
        DATABASE_URL: postgresql://postgres.yqcuewrcenhgzjmzhqtg:Typescr%21ptPr%40gr%40m%40c%40%40@aws-1-sa-east-1.pooler.supabase.com:6543/postgres?pgbouncer=true
        DIRECT_URL: postgresql://postgres:Typescr%21ptPr%40gr%40m%40c%40%40@db.yqcuewrcenhgzjmzhqtg.supabase.co:5432/postgres
        JWT_SECRET: 12fc2d4a249a1870854bb70728027ef2a227e78a0ed4101a4af3434747a839e3842eadc0723e3e9fa11ecbc18da18c6e6b922a8bfd23d3da9c0bae2bde76fd7c
        NODE_ENV: 'production'
        PORT: 3000