### Criar livro
POST http://localhost:3000/livros
Content-Type: application/json

{
    "titulo": "Clean Code",
    "autor": "Robert Martin",
    "descricao": "Livro de como escrever código limpo",
    "isbn": "978-0132350884"
}

### Listar livros
GET http://localhost:3000/livros

### Buscar livro por id
GET http://localhost:3000/livros/0

### Deletar livro
DELETE http://localhost:3000/livros/0

### Criar empréstimo
POST http://localhost:3000/emprestimos
Content-Type: application/json

{
    "livroId": 0,
    "nomeUsuario": "Ana"
}

### Listar empréstimos
GET http://localhost:3000/emprestimos/

### Buscar empréstimos por ID
GET http://localhost:3000/emprestimos/0

### Devolver empréstimo
PATCH http://localhost:3000/emprestimos/1/devolver